import { Inter } from "next/font/google";
import "./globals.css";

import NavBar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";

import { NFTMarketPlaceProvider } from "./Context/NFTMarketPlaceContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.classNameu}>
        <NFTMarketPlaceProvider>
          <NavBar />
          {children}
          <Footer />
        </NFTMarketPlaceProvider>
      </body>
    </html>
  );
}
